name: CI

on:
  push:
   branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  lint:
    name: "Lint"
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install yarn
        run: npm install -g yarn
      - name: Install Deps
        run: yarn install
      - name: Lint
        run: yarn lint

  http-test:
   name: "Jest"
   runs-on: macos-latest

   steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
       node-version: 16
    - name: Install yarn
      run: npm install -g yarn
    - name: Install Deps
      run: yarn install
    - name: Create env file
      run: |
        touch .env
        echo "${{secrets.ENV_FILE}}" > .env
    - name: Run Test
      run: yarn test-ci
