name: CI

on:
  push:
   branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  lint:
    name: "lint"
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/checkout@v2
        with:
          node-version: "17.0.0"
      - name: Install yarn
        run: npm install -g yarn
      - name: Install Deps
        run: yarn install
      - name: Lint
        run: yarn lint
